### ISSUE TITLE
module names in plot_module_matrix

### ISSUE THREAD

**Issue by maribraga** [maribraga/evolnets#4]
When running plot_module_matrix passing a data frame containing module information where modules are labeled "M1", "M2",... the order in the palette is M1, M10, M11, M2... 

If the column $module is of class `integer` then a continuous palette is used.

@Ax3man We should make sure users can pass module information as integers or strings and that both produce a discrete palette. Maybe also add an argument with the order of the modules in the palette?

**Comment by Ax3man** [comment]
Yes good points. Can you give a reprex? What is the structure of that data.frame?
